version: "3.7"

services:
  create-bucket:
   container_name: create-bucket
   hostname: create-bucket.example.com
   build: ./services/create-bucket
   working_dir: /app
   environment:
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    NODE_ENV: production
    AUTH_SVC_HOST: get-auth.example.com
    AUTH_SVC_PORT: 7001

  get-bucket-acl:
   container_name: get-bucket-acl
   hostname: get-bucket-acl.example.com
   build: ./services/get-bucket-acl
   working_dir: /app
   environment:
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    NODE_ENV: production
    AUTH_SVC_HOST: get-auth.example.com
    AUTH_SVC_PORT: 7001

  get-bucket-meta:
   container_name: get-bucket-meta
   hostname: get-bucket-meta.example.com
   build: ./services/get-bucket-meta
   working_dir: /app
   environment:
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    NODE_ENV: production
    AUTH_SVC_HOST: get-auth.example.com
    AUTH_SVC_PORT: 7001

  get-list-buckets:
   container_name: get-list-buckets
   hostname: get-list-buckets.example.com
   build: ./services/get-list-buckets
   working_dir: /app
   environment:
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    NODE_ENV: production
    AUTH_SVC_HOST: get-auth.example.com
    AUTH_SVC_PORT: 7001

  get-list-objects:
   container_name: get-list-objects
   hostname: get-list-objects.example.com
   build: ./services/get-list-objects
   working_dir: /app
   environment:
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    NODE_ENV: production
    AUTH_SVC_HOST: get-auth.example.com
    AUTH_SVC_PORT: 7001

  get-object-acl:
   container_name: get-object-acl
   hostname: get-object-acl.example.com
   build: ./services/get-object-acl
   working_dir: /app
   environment:
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    NODE_ENV: production
    AUTH_SVC_HOST: get-auth.example.com
    AUTH_SVC_PORT: 7001

  get-object-meta:
   container_name: get-object-meta
   hostname: get-object-meta.example.com
   build: ./services/get-object-meta
   working_dir: /app
   environment:
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    NODE_ENV: production
    AUTH_SVC_HOST: get-auth.example.com
    AUTH_SVC_PORT: 7001

  put-bucket-acl:
   container_name: put-bucket-acl
   hostname: put-bucket-acl.example.com
   build: ./services/put-bucket-acl
   working_dir: /app
   environment:
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    NODE_ENV: production
    AUTH_SVC_HOST: get-auth.example.com
    AUTH_SVC_PORT: 7001

  put-object-acl:
   container_name: put-object-acl
   hostname: put-object-acl.example.com
   build: ./services/put-object-acl
   working_dir: /app
   environment:
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    NODE_ENV: production
    AUTH_SVC_HOST: get-auth.example.com
    AUTH_SVC_PORT: 7001

  manage-object:
   container_name: manage-object
   hostname: manage-object.example.com
   user: "arsenal"
   build: ./services/manage-object
   working_dir: /app
   environment:
    AUTH_SVC_HOST: get-auth.example.com
    AUTH_SVC_PORT: 7001
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    RUNTIME_ENV: production
   volumes:
    - /opt/objstore:/opt/objstore
  
  get-auth:
   container_name: get-auth
   hostname: get-auth.example.com
   user: "arsenal"
   build: ./services/get-auth
   working_dir: /app
   environment:
    SERVICE_PORT: 7001
    DB_HOST: db
    DB_PORT: 27017
    RUNTIME_ENV: production

  db:
    container_name: db
    hostname: db.example.com
    image: mongo:4.2.11
    restart: always     
    volumes:
      #- /data/db_container:/data/db
      - /data/db:/data/db
    ports:
     - 27017:27017
  
  server:
   container_name: server
   hostname: server.example.com
   build: ./server
   working_dir: /app
   environment:
    CREATE_BUCKET_SVC_HOST: create-bucket.example.com
    CREATE_BUCKET_SVC_PORT: 7001
    DELETE_KEY_SVC_HOST: manage-object.local.example.com
    DELETE_KEY_SVC_PORT: 7001
    GET_BUCKET_ACL_SVC_HOST: get-bucket-acl.local
    GET_BUCKET_ACL_SVC_PORT: 7001
    GET_BUCKET_META_SVC_HOST: get-bucket-meta.local
    GET_BUCKET_META_SVC_PORT: 7001
    GET_LIST_BUCKETS_SVC_HOST: get-list-buckets.local
    GET_LIST_BUCKETS_SVC_PORT: 7001
    GET_LIST_OBJECTS_SVC_HOST: get-list-objects.local
    GET_LIST_OBJECTS_SVC_PORT: 7001
    GET_OBJECT_ACL_SVC_HOST: get-object-acl.local
    GET_OBJECT_ACL_SVC_PORT: 7001
    GET_OBJECT_META_SVC_HOST: get-object-meta.local
    GET_OBJECT_META_SVC_PORT: 7001
    PUT_BUCKET_ACL_SVC_HOST: put-bucket-acl.local
    PUT_BUCKET_ACL_SVC_PORT: 7001
    PUT_OBJECT_ACL_SVC_HOST: put-object-acl.local
    PUT_OBJECT_ACL_SVC_PORT: 7001
    GET_OBJECT_SVC_HOST: manage-object.example.com
    GET_OBJECT_SVC_PORT: 7001
    PUT_OBJECT_SVC_HOST: manage-object.example.com
    PUT_OBJECT_SVC_PORT: 7001
    LOGS_PATH: './logs'
   ports: 
    - 8080:8080
