version: "3.7"

services:
  create-bucket:
   build: ./services/create-bucket
   working_dir: /app
   environment:
    SERVICE_PORT: 8001
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8001:8001
  
  delete-key:
   build: ./services/delete-key
   working_dir: /app
   environment:
    SERVICE_PORT: 8004
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8004:8004

  get-bucket-acl:
   build: ./services/get-bucket-acl
   working_dir: /app
   environment:
    SERVICE_PORT: 8005
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8005:8005

  get-bucket-meta:
   build: ./services/get-bucket-meta
   working_dir: /app
   environment:
    SERVICE_PORT: 8009
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8009:8009

  get-list-buckets:
   build: ./services/get-list-buckets
   working_dir: /app
   environment:
    SERVICE_PORT: 8008
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8008:8008

  get-list-objects:
   build: ./services/get-list-objects
   working_dir: /app
   environment:
    SERVICE_PORT: 8007
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8007:8007

  get-object-acl:
   build: ./services/get-object-acl
   working_dir: /app
   environment:
    SERVICE_PORT: 8006
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8006:8006

  get-object-meta:
   build: ./services/get-object-meta
   working_dir: /app
   environment:
    SERVICE_PORT: 8010
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8010:8010

  put-bucket-acl:
   build: ./services/put-bucket-acl
   working_dir: /app
   environment:
    SERVICE_PORT: 8003
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8003:8003

  put-object-acl:
   build: ./services/put-object-acl
   working_dir: /app
   environment:
    SERVICE_PORT: 8002
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8002:8002

  get-object:
   build: ./services/get-object
   working_dir: /app
   environment:
    SERVICE_PORT: 8100
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8100:8100
  
  put-object:
   build: ./services/put-object
   working_dir: /app
   environment:
    SERVICE_PORT: 8101
    DB_HOST: db
    DB_PORT: 27017
   ports: 
    - 8101:8101

  db:
    image: mongo:4.2.11
    restart: always
    volumes:
      - /data/db:/data/db
  
  app:
   build: ./server
   working_dir: /app
   environment:
    PUT_SERVICE_HOST: put-object
    PUT_SERVICE_PORT: 8101
    GET_SERVICE_HOST: get-object
    GET_SERVICE_PORT: 8100
   ports: 
    - 8080:8080